[package]
name = "hightorrent_resolve"
version = "0.1.0"
edition = "2024"

[lib]
name = "hightorrent_resolve"
path = "src/lib.rs"

[[bin]]
name = "hightorrent_resolve"
path = "src/main.rs"
required-features = [ "cli" ]

[dependencies]
anyhow = "1.0.100"
async-tempfile = "0.7.0"
clap = { version = "4.5.51", features = ["derive"], optional = true }
# Opting for git until release with MagnetLink: Display
#hightorrent = "0.3.2"
hightorrent = { git = "https://github.com/angrynode/hightorrent" }
librqbit = { git = "https://github.com/ikatson/rqbit", rev = "8d99612023355076ca6439c37e88acb35bdd47bb" }
log = "0.4.28"
tokio = { version = "1.48.0", features = ["net", "rt", "macros"] }
tracing-subscriber = { version = "0.3.20", optional = true }

[features]
cli = [ "dep:clap", "dep:tracing-subscriber" ]
test_common = []
test_udp = [ "test_common" ]
test_http = [ "test_common" ]